### ISSUE TITLE
0xc0000018

### ISSUE THREAD

**Issue by shadoxxhd** [x0r19x91/010-Editor-Keygen#3]
when trying to launch main.exe (either the version from the repo or from the release page) I get a "The application was unable to start correctly (0xc0000018). Click OK to close the application." error dialog.

**Comment by shadoxxhd** [comment]
Compiling the .asm file myself didn't help either - windows shows a 'main.exe stopped working' dialog when I try to run the assembled program.

**Comment by shadoxxhd** [comment]
using windows 7 if that helps...

**Comment by shadoxxhd** [comment]
The issue comes from your new load_dll makro, though I don't know x86 asm good enough to tell you what exactly goes wrong.

**Comment by x0r19x91** [comment]
Thanks. I'll look into it
